# Generated by Django 5.2.5 on 2025-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evasue', '0002_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.IntegerField(default=13, max_length=2),
            preserve_default=False,
        ),
    ]
