# Generated by Django 5.2.5 on 2025-08-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evasue', '0003_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(max_length=2),
        ),
    ]
